### ISSUE TITLE
problog sample not behaving as in documentation

### ISSUE THREAD

**Issue by theresasturn** [ML-KULeuven/problog#101]
When I type the following command:

problog sample some_heads.pl -N 3

I get as output:

----------------
someHeads.
----------------
someHeads.
(True, <generator object sample at 0x7f5f192aca50>)

rather than 

====================
% Probability: 0.2
====================
someHeads.
% Probability: 0.2
====================
someHeads.
% Probability: 0.3

as in the documentation.  I.e., no probabilities are printed out for me.

**Comment by theresasturn** [comment]
Seems to be a general problem with sample a generator object is created, but its results are not output:

**Comment by rmanhaeve** [comment]
Hi

It seems that the output you get is an issue with the problog-cli tool. It should not be outputted. 
The documentation is also incomplete, as you need to set the --with-probabilty flag to get the desired output:
```problog sample some_heads.pl -N 3 --with-probability
someHeads.
% Probability: 0.3
----------------
someHeads.
% Probability: 0.3
----------------
someHeads.
% Probability: 0.3
(True, <generator object sample at 0x7f714a63ae40>)
```

I hope this helps in the meantime.
Kind regards,
Robin

**Comment by theresasturn** [comment]
Thank you  for responding.

In addition to looking at Problog-2 for research purposes, I'm evaluating
it for an application, along with a couple of other frameworks.  The
responsiveness of the Problog team is a big checkmark in its favor.  know
how much time that can take, believe me.

Thanks

Theresa

**Comment by sdemjanenko** [comment]
The issue appears to be `sys.exit(main())` in the CLI script that `pip` creates. If I add this to `problog-cli.py` in this repo, then I can reproduce with `python ./problog-cli.py sample test/sample/some_heads.pl -N 6`. I am not clear on where the `sys.exit(main())` is coming from. It doesn't seem to be in this repo. I see a few references:
```
conversions/uai2problog.py
321:    sys.exit(main())

conversions/bn2problog.py
216:    sys.exit(main())

conversions/smile2problog.py
105:    sys.exit(main())

conversions/hugin2problog.py
203:    sys.exit(main())

conversions/xmlbif2problog.py
150:    sys.exit(main())
```
But none of them seem to be that CLI script that gets installed.

**Comment by rmanhaeve** [comment]
Same issue as #82
