### ISSUE TITLE
Negative cycle detected.

### ISSUE THREAD

**Issue by romanilin325** [ML-KULeuven/problog#106]
Hello all, I am new to problog. I keep getting NegativeCycle: Negative cycle detected but the error does not allow to trace to a particular statement in the problog program. Is there a way to get better debug information?  What is the meaning of this error?

**Comment by wannesm** [comment]
Can you share the full message? The NegativeCycle error (or Exception if you are using Python) should also print a line number and position.

For example, when entering the following program in our [online tool](https://dtai.cs.kuleuven.be/problog/editor.html#task=prob&hash=15592769e1bef7c52236ab78f1ec621b):

    0.5::a :- \+b.
    0.5::b :- a.

    query(a).
    query(b).

The result is: `NegativeCycle: Negative cycle detected at 1:11.`, which is the location where the negation is being used and a and b are a cycle through negation (and that is a paradoxical expression).

**Comment by romanilin325** [comment]
Thank you, yes there is line number in the error message!  However, I cannot figure out what other statements in the program create the cycle.  Is there any way to print the whole cycle?

**Comment by romanilin325** [comment]
In addition, when I use --combine option, something like
>problog --combine file1.pl  file2.pl
The error message does not even have the line number, it just says
NegativeCycle: Negative cycle detected.

**Comment by rmanhaeve** [comment]
There is no way currently to print out the exact cycle. Could you perhaps show the program that is causing the issue?
