### ISSUE TITLE
MPE example in tutorial not working

### ISSUE THREAD

**Issue by GavinRens** [ML-KULeuven/problog#109]
I see [here](https://github.com/ML-KULeuven/problog/issues/65) that this issue was discussed (solved?) in October of 2021. But it still seems to be a problem, i.e., message "An unexpected error has occurred." shown when Evaluating.

**Comment by VincentDerk** [comment]
It should now work again, we restarted the webserver.

**Comment by GavinRens** [comment]
It seems to work now. Thanks!
