### ISSUE TITLE
Are constraints now supported in Problog?

### ISSUE THREAD

**Issue by deepalikholkar** [ML-KULeuven/problog#110]
Saw the class Constraint defined in the Problog 2.2 documentation. Has support for this been added..

**Comment by deepalikholkar** [comment]
Thank you for your response! Actually we wanted to encode constraints not on ground facts but as conditions that should not evaluate to true such as headless rules in ASP. We have now encoded them as Problog rules and throw an error when the rule evaluates to true.

**Comment by deepalikholkar** [comment]
We have been experimenting with DeepProblog for the past few months and its truly awesome work - the concept and mechanism of using rules to compute and feed back gradients into the neural net

**Comment by rmanhaeve** [comment]
Hi.

If your rules can be encoded as ProbLog rules you can try the following:

```
constraint :- ....
constraint :- ....

evidence(constraint, false).
```

Does this help?

**Comment by deepalikholkar** [comment]
> Hi.
> 
> If your rules can be encoded as ProbLog rules you can try the following:
> 
> ```
> constraint :- ....
> constraint :- ....
> 
> evidence(constraint, false).
> ```
> 
> Does this help?

Thanks very much for your response. This should help! Will try it out
