### ISSUE TITLE
Is approximate inference by sampling implemented in ProbLog?

### ISSUE THREAD

**Issue by andsz27** [ML-KULeuven/problog#111]
There are some papers by ProbLog team members on inference through sampling. However, I can't find out if this technique is implemented in the ProbLog interpreter. If this is the case, what interpreter options should I use to chose this technique in calculations?

**Comment by rmanhaeve** [comment]
Hi

We currently allow for you to sample possible worlds for a given query: https://problog.readthedocs.io/en/latest/cli.html#sampling-sample

Using sampling as an inference procedure is currently not implemented in the ProbLog package itself.
