### ISSUE TITLE
Extracting bounds of the anytime tp-compilation

### ISSUE THREAD

**Issue by AlexandreDubray** [ML-KULeuven/problog#112]
Hello !

In the paper "Anytime inference in probabilistic logic programs with Tp-compilation," it is described how anytime inference can be made in ProbLog.
I wondered if obtaining the evolution of the lower and upper bounds during the solving was possible.
I observed running `problog --timeout $timeout -k fsdd input.pl` will (almost) always provide an answer, even in case of timeouts.
It seems to provide a lower bound; is it possible to extract the upper bound?

**Comment by rmanhaeve** [comment]
Hi Alexandre

After reviewing it a bit further, this is indeed non-trivial to extract for now. We currently are not planning on implementing this, but we will update this issue if we do.

Kind regards,
Robin
