### ISSUE TITLE
IncosistentEvidenceError for NaiveBayesClassifier

### ISSUE THREAD

**Issue by Zarach** [ML-KULeuven/problog#117]
Hello Problog Team,

is it correct that the following program throws an inconsistent evidence error?

0.5::topic(t1).
0.5::topic(t2).

1.0::word(w1) :- topic(t1).
0.0::word(w2) :- topic(t1).
0.5::word(w3) :- topic(t1).
0.5::word(w4) :- topic(t1).

0.0::word(w1) :- topic(t2).
1.0::word(w2) :- topic(t2).
0.5::word(w3) :- topic(t2).
0.5::word(w4) :- topic(t2).

evidence(word(w1), false).
evidence(word(w2), false).
evidence(word(w3), true).
evidence(word(w4), true).

query(topic(_)).

**Comment by rmanhaeve** [comment]
Yes. word(w1) and word(22) can only both be false if both topic(t1) and topic(t2) are false. If those are false, word(w3) and word(w4) cannot be true.

**Comment by Zarach** [comment]
Oh, thanks for the fast answer! Only looked at the new added words, sorry...
