### ISSUE TITLE
SDD memory error & d-DNNF example ignoring

### ISSUE THREAD

**Issue by Zarach** [ML-KULeuven/problog#118]
Dear problog team,

I try to learn a Naive Bayes classifier for documents based on occuring words.

There are about 1000 examples and they should be classified (to be precise, the probability of the words, used at a class should be learned) like in your online example but to one of 4 classes.

If I run LFI with SDD a memory error occures.

If I run it with d-DNNF, it ignores nearly all of the given examples. 
It runs into the following error because the calculated weight is very low, even at the beginning of the learning process:

        if self.semiring.is_zero(self._get_z()):
            raise InconsistentEvidenceError(context=" during evidence evaluation")

I guess this is the wanted behavior, but could you explain in an abstract way, why examples get ignored from the beginning?
Does it mean, that there is not enough information (not enough words used) in these examples to learn parameters?

**Comment by rmanhaeve** [comment]
Hi Zarach

Could you perhaps give is an example of this behaviour?

Kind regards,
Robin

**Comment by rmanhaeve** [comment]
Hi Benjamin

It seems that you only give the training data, but there's no program attached. We'll need this as well to look into it in more depth.

**Comment by Zarach** [comment]
Hi Robin,

program_small.txt is the program which should be executable in problog standalone mode.
At least on my side this works and reproduces the problem.

**Comment by rmanhaeve** [comment]
I have solved the issue with the inconsistent evidence error by setting the initial probabilities to t(0.1) for all words, and by using log-space calculations, i.e.  by running it with 
`lfi program_small.pl examples_small.pl --logspace`

I'll now look into the memory issue
