### ISSUE TITLE
Help with board game

### ISSUE THREAD

**Issue by yonesko** [ML-KULeuven/problog#120]
I am trying to use ProbLog to solve a board game called King of the dice and there is a task to find a probability of tossing exactly N=0,1,...6 dice with value 3 out of the set of 6.

I can only come up with an ugly solution of hard-coding N.

Could somebody help, please ?

**Comment by rmanhaeve** [comment]
Perhaps this example is relevant for your case: https://dtai.cs.kuleuven.be/problog/tutorial/advanced/10_urnballmodel.html
