### ISSUE TITLE
Support hexadecimal numbers

### ISSUE THREAD

**Issue by XVilka** [ML-KULeuven/problog#19]
So this would work
```prolog
byte_alphanum(B, R) :-
    B > 0x2f, B < 0x3b, R = true.
```

**Comment by XVilka** [comment]
Is it possible to implement it? It is very annoying to convert every number just for the Problog, since the rest of interpreters work just fine.

**Comment by VincentDerk** [comment]
Unfortunately, me personally, I am very busy in the next couple of weeks so I won't be able to. We're happy to take pull requests.

**Comment by anton3s** [comment]
I've created a pull request which fixes this issue.  It's running through the checks...

**Comment by VincentDerk** [comment]
Merged it, thanks!
