### ISSUE TITLE
Question: how to define complex Python predicate

### ISSUE THREAD

**Issue by XVilka** [ML-KULeuven/problog#28]
So the predicate will have functors as the arguments?
Something like
```prolog
predicate1(functor1(Arg1, Arg2, Arg3), functor2(Arg4, Arg5, Arg6), Arg7, Out).
```
How it would look from the Python side with `@problog_export` decorator?

**Comment by anton3s** [comment]
They will be exposed in Python as Term objects.
You can use the ``term`` specifier in the problog_export decorator.

```python
@problog_export("+term", "+term", "+term", "-term")
def predicate1(a1, a2, a3):
    print(a1.functor, a1.args)
```

**Comment by XVilka** [comment]
Would be beneficial to add this in the documentation, I think.

**Comment by VincentDerk** [comment]
There is some documentation on this here: [Calling Python From ProbLog](https://problog.readthedocs.io/en/latest/modeling_advanced.html#calling-python-from-problog)

**Comment by XVilka** [comment]
Ok. Thanks! I think can be closed then.
