### ISSUE TITLE
PySDD / SDD package is not being detected in branch dcproblog_develop

### ISSUE THREAD

**Issue by shuvrobiswas** [ML-KULeuven/problog#38]
Hey guys,

Great package and research on probabilistic logic, and support for continuous probability distributions (in the dcproblog_develop branch). Looking forward to playing around with this.

There are some issues arising on the dcproblog_develop branch, on a clean ubuntu 18.04 machine with python 3.6.9 installed, after installing the dcproblog_develop branch. Running problog with the dc flag requires PySDD to be installed. I've installed this from: https://github.com/ML-KULeuven/PySDD (which requires replacing some of the files in the repo with downloaded files from: http://reasoning.cs.ucla.edu/sdd/ - would highly recommend including these in the repo to prevent user error).

When running example code involving continuous random variables, PySDD is not detected (though it is importable, works and pip3 freeze displays it):

![image](https://user-images.githubusercontent.com/1322956/71060829-93359600-2134-11ea-9c5a-8a77b4d775a8.png)

PySDD working:

![image](https://user-images.githubusercontent.com/1322956/71061480-1e635b80-2136-11ea-8b01-4ac639fea6c8.png)

(apologizes for the major updates on this installation / test run issue, have been trying to get this working for a while now!)

**Comment by wannesm** [comment]
The PySDD package you installed was not updated in the last 2 years. Can you retry installing and use the version available from PIP or https://github.com/wannesm/PySDD ?

**Comment by shuvrobiswas** [comment]
Thanks for that pointer @wannesm - looks like it's working!

![image](https://user-images.githubusercontent.com/1322956/71211929-380fba80-227e-11ea-9bce-33d3420f102b.png)
