### ISSUE TITLE
Giving a model of 500 Lines returns error on Dsharp Python

### ISSUE THREAD

**Issue by ntpapatheodorou** [ML-KULeuven/problog#47]
I'm using the library of Problog in my python project. I Have a model of 500 lines and when I try to evaluate a pop-up Command window of DSharp opens and after 1 minute it returns an error. When my model has fewer lines it works perfectly. Can you help me with this issue ?

**Comment by VincentDerk** [comment]
Can you link the model?
What is the error that is being returned?

**Comment by ntpapatheodorou** [comment]
can you share an email cause its a private work

**Comment by VincentDerk** [comment]
I have emailed you (your profile email)

**Comment by VincentDerk** [comment]
To update other viewers: the error is likely caused by running out of memory. The proposed solution is to try using '-k sdd' (which requires [PySDD](https://github.com/wannesm/PySDD); no Windows support yet) or use a machine with more RAM.
