### ISSUE TITLE
Example 3 in Naive Bayes param learning tutorial fails with "Encountered a non-ground probabilistic clause."

### ISSUE THREAD

**Issue by lewtds** [ML-KULeuven/problog#50]
https://dtai.cs.kuleuven.be/problog/tutorial/learning/03_naivebayes.html

<img width="817" alt="Screenshot 2020-12-14 at 0 50 20" src="https://user-images.githubusercontent.com/1055960/102026459-a1011400-3da6-11eb-89fc-4fa0bb7a7903.png">

**Comment by VincentDerk** [comment]
The LFI code has recently been updated to improve convergence rate.

@wenchiyang , @arcchitjain Could you have a look please? Perhaps also add these examples to the tests (both example 3 and the example at the bottom of the [page](https://dtai.cs.kuleuven.be/problog/tutorial/learning/03_naivebayes.html)).

**Comment by VincentDerk** [comment]
Also update/fix documentation: https://problog.readthedocs.io/en/latest/python.html#parameter-learning-lfi 
#60

**Comment by VincentDerk** [comment]
Should all be fixed now with v2.2.1:  d6acf3e3c55133d16b98c927a03145e22258be7b
