### ISSUE TITLE
Communicating from Python to ProbLog ?

### ISSUE THREAD

**Issue by vsraptor** [ML-KULeuven/problog#53]
Trying to run problog cmds from python following :+1: 

https://github.com/ML-KULeuven/problog/blob/master/usecases/python_interface/python_interface.ipynb

i have SDD installed , but it says it is not ??

`$ pip3 install problog[sdd] --user
Requirement already satisfied: problog[sdd] in /usr/local/lib/python3.6/dist-packages (2.1.0.39)
**Requirement already satisfied: pysdd>=0.2.6 in /usr/local/lib/python3.6/dist-packages (from problog[sdd]) (0.2.10)**
Requirement already satisfied: cython>=0.29.6 in /usr/local/lib/python3.6/dist-packages (from pysdd>=0.2.6->problog[sdd]) (0.29.21)

$ python3 chatbot.py

>!:- use_module(library(assert)).                                                                                                                                            
!:- use_module(library(assert)).
Traceback (most recent call last):
  File "chatbot.py", line 28, in <module>
    c.run()
  File "chatbot.py", line 20, in run
    print(self.exec(res[1:]))
  File "chatbot.py", line 23, in exec
    return ProbLog.convert(cmd, SDD).evaluate()
  File "/usr/local/lib/python3.6/dist-packages/problog/core.py", line 120, in convert
    next_obj = path[0](current_obj, path[1](**kwdargs), **kwdargs)
  File "/usr/local/lib/python3.6/dist-packages/problog/sdd_formula.py", line 72, in __init__
    raise InstallError('The SDD library is not available. Please install the PySDD package.')
problog.errors.InstallError: The SDD library is not available. Please install the PySDD package..`

```
from prompt_toolkit import PromptSession
from prompt_toolkit.history import FileHistory

from problog.program import PrologString
from problog.core import ProbLog
from problog.sdd_formula import SDD

 class ChatBot(object):

	def run(self):
		session = PromptSession(history=FileHistory('.chat-history'))

		while True :
			res = session.prompt('>')
			print(res)
			if res[0] == '!' :
				print(self.exec(res[1:]))

	def exec(self, cmd):
		return ProbLog.convert(cmd, SDD).evaluate()

 if __name__ == '__main__':
	c = ChatBot()			
	c.run()

```

**Comment by VincentDerk** [comment]
The SDDInstall error is thrown when one of these fails:
```
    from pysdd import sdd
    from pysdd.iterator import SddIterator
    from pysdd.util import sdd_to_dot
    from pysdd.sdd import Vtree
```
This looks like a [PySDD](https://github.com/wannesm/PySDD) installation error. Please check all the dependencies listed on that page are installed and try again using:

`pip install git+https://github.com/wannesm/PySDD.git#egg=PySDD`

If `from pysdd import sdd` persists to fail, check the Issues page of PySDD as one of those solutions might help you.
