### ISSUE TITLE
Depth of proof

### ISSUE THREAD

**Issue by alexgaskell10** [ML-KULeuven/problog#57]
I am relatively new to problog so may have missed this in the docs. I am trying to find the depth of proof used in the problog solver. i.e.
- red(bob).
- blue(X) <- red(X).
- ? blue(bob).

This problem should return a depth of 1. Is this possible in problog? If so, could you kindly point me to the relevant docs please? Thanks!

**Comment by VincentDerk** [comment]
Asked @wannesm :

> I don’t think we keep track of depth (except in the forward case). If it’s to do a post analysis one can have a look at the  and-or datastructure. Or export it with: problog ground --format dot test.pl -o test.gv
