### ISSUE TITLE
How to execute this using python

### ISSUE THREAD

**Issue by indhu-24** [ML-KULeuven/problog#60]
![IMG-20210531-WA0001](https://user-images.githubusercontent.com/85095675/120147393-3765ac80-c204-11eb-8caf-4813af788dcf.jpg)

**Comment by indhu-24** [comment]
![IMG-20210531-WA0003](https://user-images.githubusercontent.com/85095675/120160610-0c835480-c214-11eb-875f-8484b3b052ff.jpg)
While executing this program in Windows python it raises NonGroundProbabilisticClause: Encountered a non-ground probabilistic clause at 4:7

**Comment by VincentDerk** [comment]
The code you use is meant for probabilistic inference, answering specific queries, NOT for parameter learning. The reason you're seeing this error is because several probabilistic facts haven't been given any probability (p_alarm1, p_alarm2, p_alarm3,...).

As to how to call LFI from within Python, perhaps the ProbLog code can inspire you: [problog/lfi.py](https://github.com/ML-KULeuven/problog/blob/35d92989b7b49591963d5076ac5307613ebdf99e/problog/learning/lfi.py#L1576)

**Comment by indhu-24** [comment]
results = run_lfi(program, examples, knowledge=knowledge, **options) 
Can you say what the parameter knowledge here refers to. What should I give to this parameter?

**Comment by VincentDerk** [comment]
> 
> 
> results = run_lfi(program, examples, knowledge=knowledge, **options)
> Can you say what the parameter knowledge here refers to. What should I give to this parameter?

It is [based on the -k flag](https://github.com/ML-KULeuven/problog/blob/35d92989b7b49591963d5076ac5307613ebdf99e/problog/learning/lfi.py#L1551) and will [usually result](https://github.com/ML-KULeuven/problog/blob/35d92989b7b49591963d5076ac5307613ebdf99e/problog/__init__.py#L62) in either `knowledge = sdd_formula.SDD` or `knowledge = ddnnf_formula.DDNNF`

**Comment by indhu-24** [comment]
Can you please give the python code for parameter learning. It will be helpful for me,if you give the code for this example. There is NO python code for parameter learning in your website.

**Comment by VincentDerk** [comment]
> 
> 
> There is NO python code for parameter learning in your website.

https://problog.readthedocs.io/en/latest/python.html#parameter-learning-lfi

**Comment by indhu-24** [comment]
![IMG-20210531-WA0005](https://user-images.githubusercontent.com/85095675/120176908-70fadf80-c225-11eb-8177-a2ce6353e7ed.jpg)
I tried this code it raises value error.
So please give me a correct code

**Comment by VincentDerk** [comment]
cf. https://github.com/ML-KULeuven/problog/issues/50#issuecomment-851391479

Update every tuple in Examples into a triple:
e.g. `[(burglary, False), ...]` to `[(burglary, False, None), ...]`

**Comment by indhu-24** [comment]
Thank you for your quick response! I request you to fix this as quickly as possible
