### ISSUE TITLE
PySDD package not recognised

### ISSUE THREAD

**Issue by leuschel** [ML-KULeuven/problog#63]
As indicated by the KNOWN_ISSUES file, I installed PySDD on macOS (big Sur 11.4).
However, the installation does not seem to be recongised by problog:

```
python -m problog -k sdd 2_cards.pl
InstallError: The SDD library is not available. Please install the PySDD package..

leuschel@Michas-MBA13-LAN problog (master *)$ pip install pysdd
Requirement already satisfied: pysdd in /Users/leuschel/opt/miniconda3/lib/python3.8/site-packages (0.2.10)
Requirement already satisfied: cython>=0.29.6 in /Users/leuschel/opt/miniconda3/lib/python3.8/site-packages (from pysdd) (0.29.23)

$ pip install problog
Requirement already satisfied: problog in /Users/leuschel/opt/miniconda3/lib/python3.8/site-packages (2.1.0.42)
```

**Comment by GabVenturato** [comment]
Can you try to re-install pysdd with the following command and check if there are some errors during the installation?

`pip install -vvv --upgrade --force-reinstall --no-deps --no-binary :all: pysdd`

Eventually, this could directly solve the problem.

**Comment by leuschel** [comment]
Thanks, this has solved the problem!
There were no errors, but quite a few warnings (deprecation warnings and version warnings of ld such as " was built for newer macOS version (10.13) than being linked (10.9)").
