### ISSUE TITLE
Enhancement request: option to put model and examples in the same file

### ISSUE THREAD

**Issue by nathanielvirgo** [ML-KULeuven/problog#74]
For the lfi and similar features, it won't be convenient for every use case to put the examples and the model in separate files. It would be very helpful if there would be an option to put the model and the examples in the same file, e.g. with the format

```
% model code
---
% example 1
---
% example 2
```

**Comment by VincentDerk** [comment]
I prefer to have the examples in separate files myself, but I understand where you're coming from. If you wish to pursue this, regardless of whether we add support for it, you can a write wrapper method very similar to [the current one](https://github.com/ML-KULeuven/problog/blob/6e51953be59dc34734c5594c9a19990e09a7efe6/problog/learning/lfi.py#L1468) (see also the used [read_examples](https://github.com/ML-KULeuven/problog/blob/6e51953be59dc34734c5594c9a19990e09a7efe6/problog/learning/lfi.py#L1306) method).
