### ISSUE TITLE
#dinamic predicate

### ISSUE THREAD

**Issue by pudumagico** [ML-KULeuven/problog#77]
Does an option as #dynamic pred/x. exist in problog as in prolog?

**Comment by pudumagico** [comment]
Thank you Vincent!
Although I am not quite sure this is what I am looking for.
I have a program that may or not contain facts that trigger some rule, for example:
`color(a).

ans(X) :- color(X).
ans(X) :- size(X).

query(ans(X)).`

I want the program to stop bothering me about not having a fact for size(X).

**Comment by VincentDerk** [comment]
I see.

Well this is probably not the most elegant solution but my quick response would be to just add a dummy rule `x :- false.` and call it a day.

```
color(a).
size(a) :- false.  % This here will not affect the program results at all
ans(X) :- color(X).
ans(X) :- size(X).
query(ans(X)).
```

**Comment by pudumagico** [comment]
Alright, thanks a lot!
