### ISSUE TITLE
String library

### ISSUE THREAD

**Issue by Mezzenilium** [ML-KULeuven/problog#79]
A String library is listed as available in Problog documentation. But no information on its predicates is given. If this information exists, where can we find it ?

**Comment by rmanhaeve** [comment]
The provided predicates are specified in this python file, and are somewhat self-explanatory.
https://github.com/ML-KULeuven/problog/blob/master/problog/library/string.py

We will update the documentation for these, thanks for notifying us.

**Comment by Mezzenilium** [comment]
I try to use the predicates of the String library of Problog2, but it does not work or I have not understood the way to properly use them :+1: 
%:- use_module(library(lists)).
:- use_module(library(string)).

      o1(L) :- L = str2lst("aaaa, zzzz, eeee, rrrr").
      o2(S) :- S = lst2str(["aaa","dddd","fffff"]).
      o3(T) :- T = join('',["aaa","dddd","fffff"]).
      
query(o1(S)).
query(o2(S)).
query(o3(S)).

gives

o1(str2lst("aaaa, zzzz, eeee, rrrr")):	1         
o2(lst2str(["aaa", "dddd", "fffff"])):	1         
o3(join('',["aaa", "dddd", "fffff"])):	1
