### ISSUE TITLE
Regular expression search function

### ISSUE THREAD

**Issue by Mezzenilium** [ML-KULeuven/problog#83]
Is it possible to use a regular expression search function in a string offered by python, to make a Problog predicate.
If so, would it be possible to have an example of such programming?

**Comment by rmanhaeve** [comment]
I'm not entirely sure what you intend to do here. Could you perhaps clarify with a small example?

**Comment by rmanhaeve** [comment]
There's no such functionality currently in ProbLog. You could implement this functionality using the Python extern possibility as it is done in this library:
https://github.com/ML-KULeuven/problog/blob/master/problog/library/string.py

**Comment by Mezzenilium** [comment]
Ok, thank you.
