### ISSUE TITLE
problog web: ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by zhanghai4155** [ML-KULeuven/problog#89]
when run a command " problog web" in CLI, show the following information:

```
 File "d:\python\python_env\pytorch14_gpu\lib\site-packages\problog\web\server.py", line 50, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'
```

problog version: 2.2.3
python version:3.7.6
platform: win10 64bits homebasic

**Comment by VincentDerk** [comment]
According to a quick search, it's because resource is a Unix specific package.
>"resource is a Unix specific package as seen in https://docs.python.org/2/library/resource.html which is why it worked for you in Ubuntu, but raised an error when trying to use it in Windows."

https://stackoverflow.com/a/37713583
