### ISSUE TITLE
Support library(clpfd): CLP(FD): Constraint Logic Programming over Finite Domains

### ISSUE THREAD

**Issue by chiara-camilla-rambaldi-migliore** [ML-KULeuven/problog#97]
Is that possible to add the support of the clpfd library?
See [http://eu.swi-prolog.org/pldoc/man?section=clpfd](http://eu.swi-prolog.org/pldoc/man?section=clpfd) for more information.

**Comment by chiara-camilla-rambaldi-migliore** [comment]
Hi,
I'm developing a project for the University and I'm trying to solve a sudoku with DeepProbLog. The specific functionality I need to solve sudoku is the "all_distinct" predicate, the others ("ins" and "transpose") I think are replaceable by my own code. 

Kind regards,
Chiara

**Comment by rmanhaeve** [comment]
That functionality will indeed not be available any time soon, as it is very much non-trivial to implement.
